# Generated by Django 2.1 on 2018-08-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageFile',
            field=models.ImageField(blank=True, default='defaul.png', upload_to=''),
        ),
    ]
