# Generated by Django 2.1 on 2018-08-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0002_image_imagefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageFile',
            new_name='imageField',
        ),
    ]
