# Generated by Django 2.1 on 2018-08-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0003_auto_20180818_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='DefaultTitle', max_length=16),
        ),
    ]
