# Generated by Django 2.1 on 2018-09-06 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0004_auto_20180819_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(default='defaul2.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
