# Generated by Django 2.1 on 2018-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0005_auto_20180906_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageField',
            field=models.ImageField(blank=True, default='defaul.png', upload_to='images/'),
        ),
    ]
