# Generated by Django 2.1 on 2018-09-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0006_auto_20180906_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_File',
        ),
    ]
