# Generated by Django 2.1 on 2018-09-12 18:25

import ImageApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0008_auto_20180907_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_File',
            field=models.FileField(default='defaul2.png', upload_to=ImageApp.models.images_directory_path),
        ),
    ]
