# Generated by Django 2.1 on 2018-09-23 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0009_auto_20180912_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='fk_Usuario',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ImageApp.Usuario'),
        ),
    ]
