# Generated by Django 2.1 on 2018-10-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0011_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='System_user',
        ),
    ]
