# Generated by Django 2.1 on 2018-10-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0012_auto_20181003_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System_user',
        ),
    ]
