# Generated by Django 2.1.2 on 2018-11-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0016_auto_20181003_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='tiempo',
            field=models.TextField(default='Sin analisis previo', max_length=32),
        ),
    ]
